[package]
name = "csops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.69.4"

[build-dependencies]
bindgen = "0.69.4"
